
export class Patient {
  constructor(

    public address = "",
    public gener = "",
    public affiliate_type = "",
    public category_affiliate = "",
    public company = {},
    public company_id = '',
    public location = {},
    public location_id = '',
    public contract = {},
    public contract_id = '',
    public created_at = "",
    public database = "",
    public date_of_birth = "",
    public department = { id: 0, nombre: "", codigo: "" },
    public department_id = '',
    public email = "",
    public eps = { address: "", agreements_id: 0, category: "", city: "", code: "" },
    public eps_id = '',
    public firstname = "",
    public id = '',
    public identifier = '',
    public ips_principal = "",
    public level = { id: 0, number: 0, code: "", name: "", cuote: 0, },
    public level_id = '',
    public middlename = "",
    public municipality = { id: 0, department_id: 0, nombre: "", codigo: "", codigo_dane: 0 },
    public municipality_id = '',
    public phone = "",
    public regimen_type = { code: "", id: 0, name: "", created_at: "", updated_at: "" },
    public regimen_id = '',
    public regimen_types_id = '',
    public regional = { id: 0, institution_id: 0, name: "", created_at: "", updated_at: "" },
    public regional_id = '',
    public secondsurname = '',
    public state = null,
    public surname = "",
    public token = "",
    public type_document_id = '',
    public typedocument = { id: 0, code: "", dian_code: 0, name: "" },
    public updated_at = "",
    public isNew = ''

  ) { }
}
